int size(void);
int empty(void);
int front(void);
int back(void);
void push_front(int);
void push_back(int);
void erase(int);
int remove_value(int);
int value_at(int);
int value_n_from_end(int);
int pop_front(void);
int pop_back(void);
int insert(int, int);
void reverse(void);